image: rocker/verse

stages:
  - build
  - test
  - deploy

before_script:
  - echo "hello"
  # - apt-get update
  # - r -e 'install.packages(c("testthat"))'

stage1job1:
  stage: build
  script:
    - pwd
    - ls -la /
    - ls -la /
    - ls -la
    - mkdir stage1job1
    - ls -la
    # - docker build -t utbiomet/gwasapi:gitlab ./

stage1job2:
  stage: build
  script:
    - pwd
    - ls -la
    - mkdir stage1job2
    - ls -la
    # - docker build -t utbiomet/gwasapi:gitlab ./

stage2job1:
  stage: test
  script:
    - ls -la
    - mkdir testTest
# stage2job2:
#   stage: test
#   script:
#     - ls -la
#     - mkdir testTest

# deploy:
#   stage: deploy
#   script:
#     - ls -la
