image: rocker/verse

stages:
  - buildAndTest

before_script:
  - echo "hello"
  # - apt-get update
  # - r -e 'install.packages(c("testthat"))'

buildDockerImg:
  stage: buildAndTest
  image: docker:latest
  services:
    - docker:dind
  script:
    - pwd
    - ls -la
    - docker build -t utbiomet/gwasapi:gitlab ./

testAPI:
  stage: buildAndTest
  image: rocker/verse
  script:
    - R -e "5+5"
