image: rocker/verse

stages:
  - buildAndTest

before_script:
  - echo "hello"
  # - apt-get update
  # - r -e 'install.packages(c("testthat"))'

buildDockerImg:
  stage: buildAndTest
  image: docker:latest
  services:
    - docker:dind
  script:
    - pwd
    - ls -la
    # - docker build -t utbiomet/gwasapi:gitlab ./
    - docker run -d --rm --name gwasapi -p 8080:8080 utbiomet/gwasapi
    - apt-get update && apt-get install curl -y
    - 'curl -X GET "http://localhost:8080/echo?msg=it%20is%20working%20!%20" -H  "accept\: application/json"'
# testAPI:
#   stage: buildAndTest
#   before_script:
#     - apt-get update && apt-get install curl -y
#   image: rocker/verse
#   services:
#     - docker:dind
#   script:
#     - R -e "5+5"
#     - docker run -d --rm --name gwasapi -p 8080:8080 utbiomet/gwasapi
#     - 'curl -X GET "http://localhost:8080/echo?msg=it%20is%20working%20!%20" -H  "accept\: application/json"'
