image: rocker/verse

stages:
  - buildAndTest

before_script:
  - echo "hello"
  # - apt-get update
  # - r -e 'install.packages(c("testthat"))'

buildDockerImg:
  stage: buildAndTest
  image: docker:latest
  services:
    - docker:dind
  script:
    - pwd
    - ls -la
    - docker build -t utbiomet/gwasapi:gitlab ./

testAPI:
  stage: buildAndTest
  before_script:
    - apt-get update && apt-get install curl -y
  image: rocker/verse
  services:
    - utbiomet/gwasapi
  script:
    - R -e "5+5"
    - 'curl -X GET "http://localhost:8080/echo?msg=it%20is%20working%20!%20" -H  "accept\: application/json"'
